name: CI

on:
  pull_request:
    branches: [ master ]
    
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out changes
        uses: actions/checkout@v2
        
      - name: Run tests
        run: npm run test
